'classic:alternator':
  alreadyDead:
  - "{{attacker}} used alternator over {{opponent}}'s dead body. It did no effect."
  alreadyDeadPowerup:
  - 
  usedOffensiveCard:
  - "{{attacker}} used alternator on {{opponent}} but {{opponent}} used an offensive card! {{attacker}} lost **❤️ {{hpLost}}**."
  usedOffensiveCardPowerup:
  - 
  usedDefensiveCard:
  - "{{attacker}} used alternator on {{opponent}} and {{opponent}} used an defensive card! {{opponent}} lost **❤️ {{hpLost}}**."
  usedDefensiveCardPowerup:
  - 
  noEffect:
  - "{{attacker}} used alternator on {{opponent}} but it had no effect."
  noEffectPowerup:
  - 

'classic:blindshot':
  initial:
  - "{{attacker}} used blindshot and it hit..."
  initialPowerup:
  - 
  hasShield:
  - "{{victim}} was blindshotted and the attack was blocked by a shield!"
  hasShieldPowerup:
  - 
  hasReflect:
  - "{{victim}} was blindshotted and but the attack was reflected, making {{attacker}} lose **❤️ {{hpLost}}**!"
  hasReflectPowerup:
  - 
  success:
  - "{{victim}} was blindshotted and lost **❤️ {{hpLost}}**!"
  successSelf:
  - 
  successPowerup:
  - 
  successPowerupSelf:
  - 
  successLaser:
  - 
  successPowerupAndLaser:
  - 

'classic:heal':
  maxedOut:
  - "{{attacker}} tried to heal but already had the maximum amount of HP."
  success:
  - "{{attacker}} healed **❤️ {{hpGained}}**!"

'classic:laser':
  initial:
  - "{{attacker}} used laser..."
  initialPowerup:
  - 
  hasShield:
  - "{{victim}} blocked the laser with a shield!"
  hasShieldPowerup:
  - 
  hasReflect:
  - "{{victim}} reflected the laser, making {{attacker}} lose **❤️ {{hpLost}}**!"
  hasReflectPowerup:
  - 
  success:
  - "{{victim}} was hit by the laser and lost **❤️ {{hpLost}}**!"
  successPowerup:
  - 
  successLaser:
  - 
  successPowerupAndLaser:
  - 

'classic:powerup':
  success:
  - "{{attacker}} activated a power up!"

'classic:reflect':
  success:
  - "{{attacker}} activated a reflect!"

'classic:shield':
  success:
  - "{{attacker}} activated a shield!"

'classic:slash':
  alreadyDead:
  - "{{attacker}} slashed {{victim}}'s dead body."
  alreadyDeadPowerup:
  - 
  hasShield:
  - "{{attacker}} slashed {{victim}} but the attack was blocked by a shield!"
  hasShieldPowerup:
  - 
  hasReflect:
  - "{{attacker}} slashed {{victim}} but the attack was reflected, making {{attacker}} lose **❤️ {{hpLost}}**!"
  hasReflectPowerup:
  - 
  success:
  - "{{attacker}} slashed {{victim}} and lost **❤️ {{hpLost}}**!"
  successPowerup:
  - 
  successLaser:
  - 
  successPowerupAndLaser:
  - 
